management:
  endpoint:
    health:
      show-details: "ALWAYS"
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "health,info"
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    org.springframework.cloud.gateway: TRACE

server.ssl.key-store: classpath:keystore.jks
server.ssl.key-store-password: ${ssl_password}
server.ssl.key-alias: localhost
server.ssl.key-password: ${ssl_password}
server.ssl.key-store-type: PKCS12
server.ssl.enabled: true
server.port: 8080

spring.application.name: gateway

spring.zipkin.sender.type: web
spring.sleuth.reactor.instrumentation-type: decorate-on-last

app:
  admin-username: ${admin_username}
  admin-password: ${admin_password}

spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "https://lunchtime-fun.netlify.app"
            allowedMethods:
              - GET
              - POST
              - PUT
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
            exposedHeaders: "X-XSRF-TOKEN"

spring.cloud.gateway.routes:
- id: joke
  uri: http://joke
  predicates:
  - Path=/api/v1/joke/**

- id: restaurant-composite
  uri: http://restaurant-composite
  predicates:
  - Path=/api/v1/restaurants/**

- id: review-composite
  uri: http://review-composite
  predicates:
  - Path=/api/v1/reviews/**

server.shutdown: graceful
spring.lifecycle.timeout-per-shutdown-phase: 10s
---
spring.config.activate.on-profile: docker

spring.zipkin.baseUrl: http://${app.admin-username}:${app.admin-password}@zipkin-server:9411/