fullnameOverride: postgres

image:
  repository: registry.hub.docker.com/library
  name: postgres
  tag: latest
  pullPolicy: IfNotPresent

ports:
  - containerPort: 5432

volumeMounts:
  path: /var/lib/postgresql/data
  name: pgdata

volumes:
  name: pgdata
  claim: pgdata

service:
  type: NodePort
  ports:
    - port: 5432
  selector:
    app: postgres