kind: PersistentVolume
apiVersion: v1
metadata:
  name: pgdata
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/var/lib/docker/volumes/pgdata/_data"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pgdata
  labels:
    app: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi