management:
  endpoint:
    health:
      show-details: "ALWAYS"
      probes:
        enabled: true
      group:
        readiness:
          include: db
  endpoints:
    web:
      exposure:
        include: "health,info"
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true


server.port: 7005
spring.zipkin.sender.type: web

spring.application.name: site

app:
  admin-username: ${ADMIN_USERNAME:admin}
  admin-password: ${ADMIN_PASSWORD:password}

logging:
  level:
    root: INFO
    dev.kmunton.microservices: DEBUG

spring:
  jpa:
    hibernate:
      ddl-auto: update
    database: POSTGRESQL
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    initialization-mode: NEVER
    platform: postgres
    url: jdbc:postgresql://${POSTGRES_DB_HOST:localhost}:${POSTGRES_DB_PORT:5432}/${POSTGRES_DB_NAME:lunchtime}
    username: ${POSTGRES_DB_USER:testuser}
    password: ${POSTGRES_DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

server.shutdown: graceful
spring.lifecycle.timeout-per-shutdown-phase: 10s
---
spring.config.activate.on-profile: docker

server.port: 80

spring.datasource.url: jdbc:postgresql://${POSTGRES_DB_HOST}:${POSTGRES_DB_PORT}/${POSTGRES_DB_NAME}?sslmode=require
spring.datatsource.username: ${POSTGRES_DB_USER}
spring.datasource.password: ${POSTGRES_DB_PASSWORD}

spring.zipkin.baseUrl: http://${app.admin-username}:${app.admin-password}@zipkin-server:9411/
