management:
  endpoint:
    health:
      show-details: "ALWAYS"
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "health,info"
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

spring:
  jackson:
    property-naming-strategy: SNAKE_CASE

spring.application.name: geocode

app:
  admin-username: ${admin_username:admin}
  admin-password: ${admin_password:password}


server.port: 7002

spring.zipkin.sender.type: web

logging:
  level:
    root: INFO
    dev.kmunton.microservices: DEBUG

server.shutdown: graceful
spring.lifecycle.timeout-per-shutdown-phase: 10s

---
spring.config.activate.on-profile: docker

server.port: 80

spring.zipkin.baseUrl: http://${app.admin-username}:${app.admin-password}@zipkin-server:9411/